#+TITLE: 日程清单 Agenda View
#+DATE: 2023-12-05 19:25:26 +0800
#+OPTIONS: toc:nil num:t ^:t
#+PROPERTY: LANGUAGE zh
#+PROPERTY: SLUG agenda_view

* Agenda View
Agenda View 也叫日程清单，可以通过设置时间范围，文件范围，完成状态，标签(Tag)或属性(Property)等条件来筛选和生成适合各种场景的待办清单，你可以将常用的待办清单的设置保存起来以便从菜单里随时查看，你可以创建任意多个待办清单。

在日程清单中你除了可以查看待办事项之外还可以方便的进行一些操作，而不必打开对应的文件进行编辑，当你进行这些操作时 Metanote 会自动完成文件的编辑。目前可进行的操作有以下：
1. 改变 Headline 的状态，当你的待办事项进入下一个阶段时你可以这里直接修改
2. 移动或归档 Headline，当你已完成一件事情后你可以通过移动功能将它归档到另一个文件中去，比如“2023归档.org”，注意，如果 Headline 有子 Headline 则子 Headline 也会被移动
3. 删除 Headline，当你完成一件事情且没有归档的必要时可以在这里直接删除，同样，如果有子 Headline 会被一起删除
* 默认 Agenda view
默认情况下 Metanote 提供了两个待办清单"日程"和"待办事项"
** 日程
1. 日程会按时间范围(日，周，月，年)列出所的文件中有具体时间安排的 Headline，包括
   1. 计划事件(SCHEDULED)，计划某个时间做什么事情
   2. 最迟事件(DEADLINE)，某件事最迟要在什么时间完成
   3. 活跃时间戳(active timestamp)，安排在某个时间点的事情。活跃时间戳是这个样子 <2023-11-18 六>，如果你只是想记录一个时间，但并不想它出现在你的是程中或收到通知提醒，你可以使用静默时间戳，像这个样子 [2023-11-18 六]
2. 如果你查看的是“今天”的日程则会出现的 Headline 有以下：
   1. 定义在今天的事情
   2. 定义在今天之前但是未完成状态的事情，也就是说你今仍可以需要做这些事情
   3. 定义在今天之后的事情，但需要在今天提醒的事情(你可以在 Planning 中使用 waring 来设置提前几天或过期几天提醒)
3. 如果你查看的是今天之前或这后的日程，则只会出现定义在那个日期的事项。
** 待办事项
待办事项会列出所有文件下所有状态为未完成的 Headline
* 自定义 Agenda View 的设置项
以下设置项是与 Org mode 一致的，如果你熟悉 Org mode 则可以完全参考 Org mode 的设置。如果不熟悉也很容易使用，不过是一些过滤条件。
** 名称
会出现在菜单栏中以便与其它清单区分和快速访问
** Agenda files
设置文件范围，可以是单个文件或文件夹，如果不设置默认为所有文件
** 类型
日程清单有“列表”和“日程”两种类型，它们只是呈现方式不同
*** 列表
所有符合条件的 Headline 以清单形式呈现
*** 日程
1. 除自定义 Agenda view 限制的条件外，要求 Headline 必须是 SCHEDULED, DEADLINE 或和活跃时间戳的
2. 以日历的形式呈现
**** 周期
设置日程显示的时间范围
**** 每周第一天
单日程的周期为“周”时，设置每周的第一天是星期几，在其它周期时此设置项无效。
** 配置
*** 仅限未完成
是否只显示是未完成状态的 Headline，默认为选中，只显示未完成的任务
*** 子任务
是否显示子任务，默认选中，显示子任务
*** 开启 Tag 继承
选中时启用 Tag 继承，否则不启用，默认为启用
*** Tag 组
选中时启用 Tag 组，否则不启用，默认为启用
*** 开启 Property 继承
选中时启用 Property 继承，否则不启用，默认不启用
*** 计划事件，最迟事件，提醒时间戳
当选中时显示这三种任务，否则不显示。这三种任务因为有具体日期时间，通常会出现在“日程”中，所以如果你不想让它们重复出现在你的自定义清单中可以取消勾选它们。默认是显示的
*** 已注释，已归档
当选中时显示这三种任务，否则不显示。默认不显示。
** Tags 和 Properties
编辑自定义 Tag 和 Property 的过滤条件的查询字符串，完全兼容 Org mode 的 search string。每一个条件都是一个 Tag 或 Property，遵循以下设置方式
1. 支持逻辑运算符 "&" 表示“且关系”和"|"表示“或关系”，"&" 的结合优先级高于 "|"，目前不支持括号()表达式。比如:
   #+begin_example
tag1|tag2&tag3
   #+end_example
   表示查找打有 tag1 或 同时打有 tag2 和 tag3 的 Headline
2. "+" 表示正向选择，"-" 表示反选，在有 + 或 - 且没有歧义情况下可以省略 & 符。比如
   #+begin_example
+tag1+tag2-tag3
   #+end_example
   表示查找同时打有 tag1 和 tag2 且没有打 tag3 的 Headline
3. 支持正则表达式，比如
   #+begin_example
work+{^boss.*}
   #+end_example
   表示查找同时打有 work 和以 boss 开头的 tag 的 Headline
4. 当有关系运算符时表示查询条件为 Property，否则为 Tag。支持的关系运算符有 '<','=','>','<=','>=','<>'， *注意* 如果 Property 的值为字符串需使用双引号括起来，比如
   #+begin_example
+work+PRIORITY="A"+With={Sarah|Denny}
   #+end_example
   表示查找打有 work Tag 且优先级为 "A"，且有 With Property 且 Porperty 的值为 Sarah 或 Denny 的 Headline
5. 特殊 Property，前面例子中已经出现，即 PRIORITY，特殊 Property 是 Headline 本身具有属性，无需定义就已经存在，可以通过这些 Property 查找特定条件的 Headline，目前支持的特殊 Property 有以下：
   1. PRIORITY
      表示 Headline 的优先级，可用的值为 "A","B","C" 依次表示高，中，低
   2. LEVEL
      表示 Headline 有几个星号
   3. TODO
      表示 Headline 的状态关键字，注意它的值是文本，需要用双引号括起来
   4. ITEM
      表示 Headline 的标题
   5. CATEGORY
      表示 Headline 的分类
   #+begin_example
项目A+PRIORITY="A"+LEVEL=2+TODO="未完成"+CATEGORY="工作"+ITEM={.*故障.*}
   #+end_example
   表示查询分类为“工作”且打有 Tag  “项目A”，且优先级为 "A"，状态为 "未完成"，标题中包含 "故障" 文案的 Level 为 2 的 Headline
