#+TITLE: Change Log
#+DATE: 2023-12-04 16:14:02 +0800
#+OPTIONS: toc:nil num:nil ^:t p:t
#+PROPERTY: SLUG changelog
#+PROPERTY: LANGUAGE en

* 0.22.0
CLOSED: [2025-03-24 一]
Optimized product interaction and improved stability.

1. Recent files and full-text search have been moved to the sidebar. Now these two functions can be accessed directly from the sidebar.
2. Support one-click creation of files and folders from the file list
3. The sorting of the file list supports setting whether folders are prioritized
4. Fixed the problem that inherited tags cannot be displayed when editing tags
5. *scratch* buffer supports the functions of Refile, archiving and adding attachments
6. Capture template supports separate settings for whether to use mini buffer
7. Other details optimization and problem fixes
* 0.21.1
CLOSED: [2025-03-19 三]
Support archiving.

1. Supports both internal archiving (with 'ARCHIVE' tag) and archiving to other files
2. You can set the default archiving action in the settings
3. Supports setting the archiving path, target headline and whether to use datetree
4. Supports setting the context information to be recorded when archiving
5. Supports global archiving settings and inBufferSettings. With inBufferSettings, you can archive tasks in different files to different locations
6. Now you can trigger the archiving action with one click in the editor or agenda view
* 0.20.0
CLOSED: [2025-02-26 三]
1. Implemented interactive visual tag editing
   1. Support group tag
   2. Support mutually exclusive group
   3. Support regular expression tags
2. Support editing to-do status, priority, tag, etc. directly from the agenda view through remote edit
3. Solved the related issues when customizing capture template
4. Solved the crash problem when highlighting code blocks on some mobile phones.
5. Other bug fixes
* 0.19.0
CLOSED: [2025-01-27 一]
- Support latex environment, latex fragment.
- Support org mode entity
- bugfix
* 0.18.0
CLOSED: [2025-01-11 六]
1. Src block supports syntax highlighting. Support most mainstream development languages and highlighting themes.
2. bugfix
* 0.17.1
CLOSED: [2024-12-31 二]
The user interaction design has been greatly optimized. Now it is not only powerful, but also easier to use.

Note that starting from this version, the gesture operation changes to swiping left from the edge of the screen to go backward and close, and swiping left from non-edge to open the navigation drawer. This is because on the one hand it is unified with the standard side slide return gesture of iOS, and on the other hand it can effectively reduce misoperations.

- Fast accessor supports setting whether to automatically activate the search bar
- Fast accessor supports setting file sorting method
- Other bugfix
* 0.17.0
CLOSED: [2024-12-20 五]
The user interaction design has been greatly optimized. Now it is not only powerful, but also easier to use.
* 0.16.0
CLOSED: [2024-12-06 六]
- Supports displaying images in file links and attachments.
- Fixed the problem of not having permission when inserting attachments.
- Fixed some  other issues.
* 0.15.0
CLOSED: [2024-11-29 五]
1. Hyperlinks and attachments
   1. Supports jumping, inserting and editing of internal and external links.
   2. Supports opening, previewing and editing the following types of attachments:
      1. iWork and Microsoft Office documents
      2. Images
      3. Live Photos
      4. Text files
      5. PDFs
      6. Audio and video files
2. Supports folding or expanding headlines by left swiping or double-clicking.
3. Supports going backward by swiping right.

See [[file:../hyperlinks_and_attachments.html][Hyperlinks and attachments]]

* 0.14.1
CLOSED: [2024-11-10 日]
This is a very important version. In this version we have implemented a more modern display of Org mode than in Emacs. Tables and blocks can be layout and rendered independently. In this version, you can easily browse and edit tables and code blocks on your mobile phone without being limited by the screen size of your mobile phone. And this is just the beginning.

1. Supports Org mode’s Visibility Cycling
2. Currently you can switch the collapsed and expanded state of Subtree through TAB key
3. Supports the independent layout of tables and code blocks. You can see the same table effect as in Emacs on your mobile phone without being limited by the screen size. Of course, you can still edit them smoothly.
4. Supports independent layout and rendering of other blocks, you can even nest other blocks within the block
5. Fix other issues.
* 0.13.0
CLOSED: [2024-09-28 六]
1. Slide menu is back.
2. Support floating action button (FAB)
3. Support insert template content
4. Support backward and forward button
5. Multiple user experience improvements.
* 0.12.1
CLOSED: [2024-06-28 五]
1. Confirmation is required before clearing the scratch buffer.
2. The start page can be set to a specific file or folder and cannot be closed.
3. Optimized the display of the settings page.
4. The initial path when opening a file is set to the root directory of the default location.
5. New file content templates are now set independently instead of using capture templates.
6. Agenda view supports swipe gestures to change status.
7. Agenda view now supports displaying category, tags, and priority.
* 0.12.0
CLOSED: [2024-06-25 二]
We continuously explore ways to optimize Metanote through practical use, and this latest upgrade might be the best experience yet. Our developers have started using Metanote heavily in their daily development work to record and manage progress. With thousands of org documents seamlessly integrated with Emacs and real-time synchronization, Metanote has become as essential to us as Emacs. We have shared on our official website how to synchronize with Emacs in real-time and some practical use cases of how we use Metanote daily for your reference.

This update includes:
1. Overall optimization of interaction and interface.
2. Support for directly opening external files.
3. Support for *scratch* buffer.
4. Editor support for adjusting font size.
5. Editor support for auto-hiding and displaying the navigation bar and toolbar.
6. Performance optimization for full-text search.
7. Newest added headlines in the agenda view and todo list will be listed at the top.
8. Opening content in the agenda and task list will automatically narrow to specific subtree.
9. Narrow buffer now supports widen.
10. Optimization of buffer list management.

* 0.11.0
CLOSED: <2024-04-24 三>
Major update: Sync support is now available.

Metanote supports various sync methods to seamlessly connect your documents between your computer and iPhone. You can configure sync in the settings, including local directories, Git, iCloud, Dropbox, OneDrive, WebDAV (Apache WebDAV Server, ownCloud, Yandex.disk, etc.). Local directories, Git, and iCloud are implemented by adding external folders, while other methods have built-in sync. Sync is fully automatic, and you hardly need to trigger it actively. In most cases, when you need it, your latest files are already there. You can use Metanote as a data center, syncing with different directories and different cloud services, or syncing with multiple cloud services on the same directory. Feel free to explore more ways to use it.

* 0.10.1
CLOSED: <2024-04-08 一>
1. Fixed issues after upgrading to iOS 17.4.1.
2. Fixed issues on iOS 14.x.
3. Fixed other user-reported issues.
* 0.10.0
CLOSED: <2024-03-26 二>
1. Automatic updates for agenda views and to-do list are now supported. Whether you edit files in Metanote or use other app to edit files in external folders, or retrieve updates from iCloud or Git, Metanote can now automatically detect changes to files and update them accordingly. Your content will always stay up to date.
2. Agenda Filter support is now available, allowing you to filter schedules and to-do items directly by category, todo keyword, and tag.
3. Buffer outlines now support clicking to jump to a specific headline.
4. Customization of Todo Keyword icons and colors is now possible.
5. More intuitive and convenient multi-buffer management is now provided. You can now directly switch buffers from the Buffer list.
6. Various other optimizations have been made, resulting in increased stability.

   
Regarding file synchronization, Metanote can add any external directory that supports folder-level File Provider and automatically detect file updates. Unfortunately, many cloud drives only support file-level File Provider. We have implemented the ability to add individual files to Metanote, which is still in testing and is expected to be launched in next version. Therefore, the best regular file synchronization solutions for now are:
1. iCloud, which supports folder-level File Provider and can be directly added to Metanote.
2. Git, where most Git app's directories can be directly added to Metanote. For example, with PolyGit, when you git pull, Metanote will automatically update the file content.
3. Other apps that support synchronization. Most document editing apps can be directly added to Metanote, such as Obsidian and Logseq. When files in these apps are updated, Metanote will automatically handle the edited files.
* 0.9.0
CLOSED: <2024-02-19 一>
Refreshed and revamped!
1. Redesigned the logo.
2. Completely optimized the main interactive experience, supporting sidebars and more mobile-friendly swipe actions for efficient and smooth use.
3. Focused on optimizing the keyboard design:
   - Features are centralized and clear.
   - Added support for sound feedback.
   - Enabled cursor movement with the joystick.
4. Added support for hiding files and folders.
5. Added the ability to add working directories for Obsidian and Logseq, integrating and managing them uniformly.
6. Supported customization of the startup page.
7. Enabled opening the current content in a new tab.
8. Various detailed optimizations and bug fixes.
* 0.8.0
CLOSED: <2024-02-01 四>
Finally, the development and testing of the custom Capture feature are complete! This process not only presented some technical challenges but also involved a substantial amount of work. There are many usage scenarios to support, and the testing alone took nearly two weeks.

With this, Metanote's support for the core features of Org mode is more comprehensive, including basic document structure, custom task management, custom InBufferSettings like tags, Agenda views, custom Capture, and more. I believe Metanote is now one of the most complete applications supporting Org mode outside of Emacs. In future development, we will gradually introduce support for rich text rendering, including images, tables, hyperlinks, encryption, export functions, Roam Research, and more. Stay tuned.

At the same time, we've initiated the public beta version. You can install both the official and beta versions at same time, join the public test, and provide feedback. https://testflight.apple.com/join/pAYGdOQe , Please note that the beta version may have some bugs and is intended for testing purposes only.

Updates in this release:
1. Added support for custom Capture feature. For detailed settings and usage, please refer to the official website: https://metanote-dev.github.io/
2. Moved all functions that open new buffers, including capture, agenda view, file manager, favorites, etc., to the left menu in the navigation bar.
3. The 'Drafts' feature, now functioning as a Capture template, is no longer independent and has been removed from the file manager.
4. The 'Favorites' feature is now a separate buffer and has been removed from the file manager.
5. Optimized the functions of the MiniBuffer and Narrow Buffer.
* 0.7.1
CLOSED: <2023-12-11>
1. Fixed the issue where custom Agenda views of the Agenda type could not be deleted.
2. Fixed the issue where there were two “Settings” entries in the menu.
* 0.7.0
CLOSED: <2023-11-18>
By now, we support all the settings for the custom agenda view feature in Org mode. If you find any omissions, please report the issues to us.

Next step, we will support the "Custom capture" feature. Stay tuned!

1. Custom agenda view now supports agenda types, allowing you to view to-do items by day, week, month, and year.
2. Custom agenda views can now be saved directly from agenda view.
3. Agenda view defaults to displaying all to-do items for the current week.
4. The default global to-do list only shows incomplete items.
5. The entry points for Capture and Agenda View have been unified into the More menu.
6. Various details and user experience optimizations have been implemented.
* 0.6.0
CLOSED: <2023-11-03>
Exciting features! Now supporting custom agenda views! You can customize your to-do lists based on CATEGORY, TAG, PROPERTY, TODO keywords, etc., and save them for easy access and review.

1. Customizable agenda views supported
2. Support for Tags, including Tag Groups, refer to the help documentation for details
3. Support for Properties, including custom Properties and Special Properties. Currently supported Special Properties include PRIORITY, LEVEL, TODO, ITEM, CATEGORY. Refer to the help documentation for details.
4. Support for InBufferSettings, refer to the documentation. Currently supported settings include TITLE, DATE, CATEGORY, PROPERTY, TODO, SEQ_TODO, TYP_TODO, FILETAGS, TAGS.
5. Window switching effects optimized, along with multiple user experience enhancements.
* 0.5.0
CLOSED: <2023-09-22>
Metanote is currently in a fast-paced development phase, and as we progress with our development work, we will bring more convenient and useful features, aiming to become the best note, calendar, and to-do list tool. We appreciate the support and encouragement from our early users.

1. In this version, we have introduced the option to make a one-time purchase for permanent access to all Metanote premium features!
2. Added support for iPad!
3. Added support for moving and renaming files or folders, making it easier for you to manage your drafts and flashes.
4. Multiple user experience improvements and refinements.
* 0.4.0
CLOSED: <2023-09-08>
Major Update!
Three highly useful features:
1. Local notifications are now supported! Receive reminders for SCHEDULED, DEADLINE, and ACTIVE planning.
2. Introducing Today's Agenda View! Easily check what you need to do today with just one tap!
3. Customize your to-do keywords! Say goodbye to TODO and DONE; you can now set your unique keywords like 'LATER,' 'CANCELED,' or whatever suits your workflow best. Let your imagination run wild!

Experience Improvements:
1. The screen stays lit while editing, giving you more time to think.
2. Timestamp editing has been optimized.
3. Capture from shortcuts!

The app is in its early stages of rapid development, so stay tuned for updates – there are always exciting features coming your way!
* 0.3.0
CLOSED: <2023-08-22>
1. Support Drafts! Now your can capture drafts!
2. a better file browser
3. Support set default location
4. move cursor quickly
5. editor support dark mode and better font color
* 0.2.1
CLOSED: <2023-08-11>
1. bugfix
* 0.2.0
CLOSED: <2023-08-07>
1. Support adding locations! Support iCloud or other file provider.
2. Support remove auto-fill mode.
3. bug fix
* 0.1.0
CLOSED: <2023-07-27>
1. An incredibly smooth editing experience.
2. Compatible with org mode version 9.3.6
3. Supports capture, agenda view, refile, log note and more.
4. Supports mini buffer and remote edit.
5. Supports multi-window editing.
6. Supports full-text search.
