#+TITLE: 更新日志
#+DATE: 2023-12-04 16:14:02 +0800
#+OPTIONS: toc:nil num:nil ^:t p:t
#+PROPERTY: SLUG changelog
#+PROPERTY: LANGUAGE zh

* 0.17.0
CLOSED: [2024-12-20 五]
大幅优化了产品交互，现在不只强大，而且更好用了。
* 0.16.0
CLOSED: [2024-12-06 六]
- 支持了直接渲染和显示文档链接和附件中的图片
- 修复插入附件时提示没有权限的问题
- 修复多个其它问题
* 0.15.0
CLOSED: [2024-11-29 五]
1. 支持了文档链接和附件
   1. 支持内部和外部文档链接的跳转，插入和编辑
   2. 支持打开，预览和编辑以下类型附件
      1. iWork and Microsoft Office documents
      2. Images
      3. Live Photos
      4. Text files
      5. PDFs
      6. Audio and video files
2. 支持了通过左划或双击折叠或展开 headline
3. 支持了通过右划返回上一页

链接与附件详见 [[file:../hyperlinks_and_attachments.html][文档链接和附件]]
* 0.14.1
CLOSED: [2024-11-10 日]
这是一个非常重要的版本，在这个版本中我们实现了比 Emacs 中更为现代化的 Org mode 的显示，表格和 blocks 可以独立布局和渲染。您在这个版本中可以方便的在手机中浏览和编辑表格和代码块而不受手机屏幕大小的限制。而这仅仅只是个开始。

1. 支持了 Org mode 的 Visibility Cycling
2. 目前您可以通过 TAB 键切换 Subtree 的折叠和展开状态
3. 支持了表格和代码块的独立布局，您可以在手机中看到和 Emacs 中一样的表格的效果而不受屏幕大小的限制，当然，您仍旧可以流畅的编辑它们。
4. 支持了其它 block 的独立布局和渲染，您甚至可以在 block 中嵌套其它 block
5. 修复其它问题。
* 0.13.0
CLOSED: [2024-09-28 六]
1. 左边栏回归了
2. 支持了悬浮按钮，即使是在编辑内容时也可以快速的访问常用功能
3. 更合理的交互
4. 提升了稳定性
* 0.12.1
CLOSED: [2024-06-28 五]
1. 清空 scratch buffer 前需要确认
2. 起始页支持设置为某一文件或文件夹，且不可关闭
3. 优化了设置页的显示
4. 打开文件时初始路径为默认位置的根目录
5. 新文件内容模版不再使用 capture template，而是可以独立设置了
6. agenda view 支持侧滑变更状态
7. agenda view 支持显示 category, tags 和优先级了
* 0.12.0
CLOSED: [2024-06-25 二]
我们不断在实践中探索优化 Metanote，这次升级的版本可能是目前以来体验最好的版本。我们内部开发人员已经开始在日常的开发工作中重度使用 Metanote 记录和管理开发进度，上千份 org 文档与 Emacs 之间无缝衔接，实时同步，它已对于我们来说已经同 Emacs 一样重要。我们在我们的官网分享了如何与 Emacs 之间实时同步以及我们日常使用 Metanote 的一些实践案例，以供您参考。

本次更新内容：
1. 整体优化了交互和界面
2. 支持了直接打开外部文件
3. 支持 scratch buffer
4. 编辑器支持了调整字体大小
5. 编辑器支持自动隐藏显示导航栏和工具栏
6. 优化了全文搜索的性能
7. 日程和待办列表中最新添加事件将排在最前
8. 日程和待办列表中打开内容将自动 Narrow 到具体内容
9. Narrow buffer 支持了 widen
10. 优化了多窗口管理
* 0.11.0
CLOSED: <2024-04-24 三>
重要更新，现在可以支持同步了。

Metanote 支持多种同步方式使您的文档可以在电脑与手机间无缝衔接，您可以在设置中配置同步，包括本地目录，Git, iCloud, Dropbox, OneDrive, WebDAV(自建 WebDAV Server, ownCloud, Yandex.disk, 坚果云等)，其中本地目录，Git 与 iCloud 通过添加外部文件夹实现，其它方式内置同步。同步是全自动的，您几乎不用主动触发，大部分情况下当您需要时，您最新的文件已经在那里了。您可以将 Metanote 做为数据中心，使用不同的目录与不同的云服务同步，也可以在同一个目录上同时与多个云端同步，更多玩法请尽情探索。
* 0.10.1
CLOSED: <2024-04-08 一>
1. 修复了升级 iOS 17.4.1 后的兼容性问题
2. 修复了 iOS 14.x 上的兼容性问题
3. 集中修复了多个用户反馈问题
* 0.10.0
CLOSED: <2024-03-26 二>
1. 支持了自动更新日程和待办事项，无论是在 Metanote 中编辑了文件还是使用其它工具编辑了外部文件夹中的文件，又或者是从 iCloud 或 Git 中获取了更新，现在 Metanote 都能自动检测到文件的变化，并自动更新，您所有的内容都将随时保持最新。
2. 支持了 Agenda Filter，现在您可以在日程和待办事项中直接通过分类，状态以及 Tag 标签进行筛选了
3. 文档大纲支持点击跳转到某个标题了
4. 可以自定义 Todo Keyword 的图标和颜色了
5. 更加直观方便的多窗口管理，现在您可以从 Buffer list 中直接点击切换窗口了
6. 其它多个细节优化，现在更加稳定了


关于文件同步的说明，Metanote 可以添加任何支持文件夹级 File Provider 的外部目录并自动感知文件更新，但可惜的是很多云盘只支持了文件级的 File Provider，我们已经实现了添加独立文件到 Metanote 中，仍在测试中，预计会在一个版本中上线。所以目前体验最好的常规文件同步方案有
1. iCloud，iCloud 支持文件夹级的 File Provider，可以直接添加进 Metanote
2. Git，多数 Git 应用的目录都可以直接添加进 Metanote，拿 PolyGit 举例，当您 git pull 时 Metanote 将自动更新文件内容
3. 其它支持同步的应用，多数文档编辑类应用都可以直接添加进 Metanote，比如 Obsidian 和 Logseq，当这些应用中的文件发生更新时 Metanote 将自动处理发生编辑的文件。
* 0.9.0
CLOSED: <2024-02-19 一>
焕然一新!
1. 重新设计了 Logo
2. 全面优化了主体交互体验，支持了侧边栏和更适合手机的滑动操作，高效流畅
3. 集中优化了软键盘的设计
   1. 功能集中且清晰
   2. 支持了按键音反馈
   3. 支持了轨迹球移动光标
4. 支持了隐藏文件和文件夹
5. 支持添加 Obsidian 和 Logseq 工作目录，整合并统一管理和编辑
6. 支持定制启动页
7. 支持在新窗口打开当前内容
8. 多个细节优化和问题修复
* 0.8.0
CLOSED: <2024-02-01 四>
终于，自定义 Capture 功能的开发和测工作完成了！这个过程不但有一些技术挑战，而且有着很大的工作量，有非常多的使用场景需要支持，单是测试工作就用了将近两周。

至此，Metanote 对 Org mode 的核心功能的支持更加完备，包括基本的文档结构，自定义任务管理，自定义 Tag 等 InBufferSettings, 自定义 Agenda view，自定义 Capture 等等，我想 Metanote 应该是在 Emacs 之外对 Org mode 支持最完整的应用了。在后面的开发工作中我们将逐渐支持富文本渲染，包括图片，表格，超链接等，以及加密，导出，Roam Research 等功能，敬请期待。

同时我们启用了公测版本，您可以同时安装正式版和测试版，加入公测，反馈问题， https://testflight.apple.com/join/pAYGdOQe (注意，测试版本可能会存在一些问题，仅供测试使用)

本次更新内容:
1. 支持自定义 Capture 功能，详细设置和使用请参考官网 https://metanote-dev.github.io/
2. 所有打开新窗口(Buffer)的功能的入口，包括 capture, agenda view, 文件管理器，收藏等，移至导航栏左侧菜单
3. “草稿”功能做为一个 Capture 模版不再独立存在，从文件管理器中移除
4. “收藏”功能独立为一个窗口(Buffer)，从文件管理器中移除
5. 优化了 MiniBuffer 和 Narrow Buffer 的功能
* 0.7.1
CLOSED: <2023-12-11>
1. 修复了无法删除日程类型自定义 Agenda view 的问题
2. 修复了编辑器菜单中有出现两个"设置"入口的问题
* 0.7.0
CLOSED: <2023-11-18>
至此 Custom agenda view 功能完整了，Org mode 中 Custom agenda view 功能的所有设置项都已支持(如果有遗漏请报问题给我们)。

下一步我们将全面支持 Custom capture 功能，敬请期待！

1. Custom agenda view 现在支持 Agenda 类型，可以按日，周，月和年时间范围查看待办事项
2. 自定义 Agenda view 可以直接保存了
3. 日程默认显示本周所有的待办事项
4. 默认全局待办列表只显示未完成项目
5. Capture 和 Agenda view 功能入口统一到了更多菜单中
6. 多个细节体验优化
* 0.6.0
CLOSED: <2023-11-03>
重磅功能，支持了自定义待办清单(Agenda View)! 可以根据 CATEGORY, TAG, PROPERTY, TODO 关键字等自定义待办清单，并可保存以供随时访问查看。

1. 支持自定义待办清单(Agenda View)
2. 支持 Tag，包括 Tag Group，详见帮助文档
3. 支持 Property，包括自定义 Property 和 Special Property，目前支持的 Special Property 包括 PRIORITY, LEVEL, TODO, ITEM, CATEGORY, 详见帮助文档
4. 支持 InBufferSettings ，详见文档，目前支持的包括 TITLE,DATE,CATEGORY,PROPERTY,TODO,SEQ_TODO,TYP_TODO,FILETAGS,TAGS
5. 窗口切换效果优化等多处体验优化
* 0.5.0
CLOSED: <2023-09-22>
Metanote 目前处于高速开发过程中，随着我们开发工作的进行，我们会带来更多便利好用的功能，并成为最好的笔记，日程和待办清单工具。感谢早期用户对我们的支持和鼓励。

1. 在这个版本中我们支持了对 Metanote 所有高级功能的一次性永久买断！
2. 支持了 iPad!
3. 支持了移动和重命名文件或文件夹。这样您就可以更方便的管理您的草稿和闪现。
4. 多个体现细节优化
* 0.4.0
CLOSED: <2023-09-08>
重大更新！
三个非常实用的功能
1. 支持本地通知了！对于编辑的计划事件，最迟事件和日程可以在安排的时间通知提醒了！
2. 支持今日聚合视图！一键查看今天要做的事！
3. 自定义待办关键字！告别 TODO 和 DONE，你可以设置自己独有的关键字，比如“稍后”，“取消”，所有你能想到的，发挥想象力，找到最合适自己的工作流！

体验优化
1. 编辑时屏幕常亮，现在可以慢慢思考了
2. 优化了时间戳的编辑
3. 支持快捷启动，闪现功能从主屏屏一键开启

App 正处于早期高速开发阶段，请保持关注和更新，总会有一些功能让你心动！
* 0.3.0
CLOSED: <2023-08-22>
1. 支持快速记录闪现
2. 更好的文件管理器
3. 支持设置默认位置
4. 更方便的移动光标
5. 编辑器支持深色模式，并优化了字体颜色
6. 优化了多个交互细节
* 0.2.1
CLOSED: <2023-08-11>
1. 问题修复
* 0.2.0
CLOSED: <2023-08-07>
1. 支持增加外部文档位置
2. 支持移除 auto-fill mode.
3. 问题修复
* 0.1.0
CLOSED: <2023-07-27>
1. 流畅丝滑的编辑体验
2. 兼容 org mode 9.3.6
3. 支持 capture, agenda view, refile, log note 等功能
4. 支持 mini buffer, remote edit
5. 支持多窗口编辑
6. 支持全文搜索
