#+TITLE: Change Log
#+DATE: 2023-12-04 16:14:02 +0800
#+OPTIONS: toc:nil num:nil ^:t p:t
#+PROPERTY: SLUG changelog
#+PROPERTY: LANGUAGE en

* 0.11.0
CLOSED: <2024-04-24 三>
Major update: Sync support is now available.

Metanote supports various sync methods to seamlessly connect your documents between your computer and iPhone. You can configure sync in the settings, including local directories, Git, iCloud, Dropbox, OneDrive, WebDAV (Apache WebDAV Server, ownCloud, Yandex.disk, etc.). Local directories, Git, and iCloud are implemented by adding external folders, while other methods have built-in sync. Sync is fully automatic, and you hardly need to trigger it actively. In most cases, when you need it, your latest files are already there. You can use Metanote as a data center, syncing with different directories and different cloud services, or syncing with multiple cloud services on the same directory. Feel free to explore more ways to use it.

* 0.10.1
CLOSED: <2024-04-08 一>
1. Fixed issues after upgrading to iOS 17.4.1.
2. Fixed issues on iOS 14.x.
3. Fixed other user-reported issues.
* 0.10.0
CLOSED: <2024-03-26 二>
1. Automatic updates for agenda views and to-do list are now supported. Whether you edit files in Metanote or use other app to edit files in external folders, or retrieve updates from iCloud or Git, Metanote can now automatically detect changes to files and update them accordingly. Your content will always stay up to date.
2. Agenda Filter support is now available, allowing you to filter schedules and to-do items directly by category, todo keyword, and tag.
3. Buffer outlines now support clicking to jump to a specific headline.
4. Customization of Todo Keyword icons and colors is now possible.
5. More intuitive and convenient multi-buffer management is now provided. You can now directly switch buffers from the Buffer list.
6. Various other optimizations have been made, resulting in increased stability.

   
Regarding file synchronization, Metanote can add any external directory that supports folder-level File Provider and automatically detect file updates. Unfortunately, many cloud drives only support file-level File Provider. We have implemented the ability to add individual files to Metanote, which is still in testing and is expected to be launched in next version. Therefore, the best regular file synchronization solutions for now are:
1. iCloud, which supports folder-level File Provider and can be directly added to Metanote.
2. Git, where most Git app's directories can be directly added to Metanote. For example, with PolyGit, when you git pull, Metanote will automatically update the file content.
3. Other apps that support synchronization. Most document editing apps can be directly added to Metanote, such as Obsidian and Logseq. When files in these apps are updated, Metanote will automatically handle the edited files.
* 0.9.0
CLOSED: <2024-02-19 一>
Refreshed and revamped!
1. Redesigned the logo.
2. Completely optimized the main interactive experience, supporting sidebars and more mobile-friendly swipe actions for efficient and smooth use.
3. Focused on optimizing the keyboard design:
   - Features are centralized and clear.
   - Added support for sound feedback.
   - Enabled cursor movement with the joystick.
4. Added support for hiding files and folders.
5. Added the ability to add working directories for Obsidian and Logseq, integrating and managing them uniformly.
6. Supported customization of the startup page.
7. Enabled opening the current content in a new tab.
8. Various detailed optimizations and bug fixes.
* 0.8.0
CLOSED: <2024-02-01 四>
Finally, the development and testing of the custom Capture feature are complete! This process not only presented some technical challenges but also involved a substantial amount of work. There are many usage scenarios to support, and the testing alone took nearly two weeks.

With this, Metanote's support for the core features of Org mode is more comprehensive, including basic document structure, custom task management, custom InBufferSettings like tags, Agenda views, custom Capture, and more. I believe Metanote is now one of the most complete applications supporting Org mode outside of Emacs. In future development, we will gradually introduce support for rich text rendering, including images, tables, hyperlinks, encryption, export functions, Roam Research, and more. Stay tuned.

At the same time, we've initiated the public beta version. You can install both the official and beta versions at same time, join the public test, and provide feedback. https://testflight.apple.com/join/pAYGdOQe , Please note that the beta version may have some bugs and is intended for testing purposes only.

Updates in this release:
1. Added support for custom Capture feature. For detailed settings and usage, please refer to the official website: https://metanote-dev.github.io/
2. Moved all functions that open new buffers, including capture, agenda view, file manager, favorites, etc., to the left menu in the navigation bar.
3. The 'Drafts' feature, now functioning as a Capture template, is no longer independent and has been removed from the file manager.
4. The 'Favorites' feature is now a separate buffer and has been removed from the file manager.
5. Optimized the functions of the MiniBuffer and Narrow Buffer.
* 0.7.1
CLOSED: <2023-12-11>
1. Fixed the issue where custom Agenda views of the Agenda type could not be deleted.
2. Fixed the issue where there were two “Settings” entries in the menu.
* 0.7.0
CLOSED: <2023-11-18>
By now, we support all the settings for the custom agenda view feature in Org mode. If you find any omissions, please report the issues to us.

Next step, we will support the "Custom capture" feature. Stay tuned!

1. Custom agenda view now supports agenda types, allowing you to view to-do items by day, week, month, and year.
2. Custom agenda views can now be saved directly from agenda view.
3. Agenda view defaults to displaying all to-do items for the current week.
4. The default global to-do list only shows incomplete items.
5. The entry points for Capture and Agenda View have been unified into the More menu.
6. Various details and user experience optimizations have been implemented.
* 0.6.0
CLOSED: <2023-11-03>
Exciting features! Now supporting custom agenda views! You can customize your to-do lists based on CATEGORY, TAG, PROPERTY, TODO keywords, etc., and save them for easy access and review.

1. Customizable agenda views supported
2. Support for Tags, including Tag Groups, refer to the help documentation for details
3. Support for Properties, including custom Properties and Special Properties. Currently supported Special Properties include PRIORITY, LEVEL, TODO, ITEM, CATEGORY. Refer to the help documentation for details.
4. Support for InBufferSettings, refer to the documentation. Currently supported settings include TITLE, DATE, CATEGORY, PROPERTY, TODO, SEQ_TODO, TYP_TODO, FILETAGS, TAGS.
5. Window switching effects optimized, along with multiple user experience enhancements.
* 0.5.0
CLOSED: <2023-09-22>
Metanote is currently in a fast-paced development phase, and as we progress with our development work, we will bring more convenient and useful features, aiming to become the best note, calendar, and to-do list tool. We appreciate the support and encouragement from our early users.

1. In this version, we have introduced the option to make a one-time purchase for permanent access to all Metanote premium features!
2. Added support for iPad!
3. Added support for moving and renaming files or folders, making it easier for you to manage your drafts and flashes.
4. Multiple user experience improvements and refinements.
* 0.4.0
CLOSED: <2023-09-08>
Major Update!
Three highly useful features:
1. Local notifications are now supported! Receive reminders for SCHEDULED, DEADLINE, and ACTIVE planning.
2. Introducing Today's Agenda View! Easily check what you need to do today with just one tap!
3. Customize your to-do keywords! Say goodbye to TODO and DONE; you can now set your unique keywords like 'LATER,' 'CANCELED,' or whatever suits your workflow best. Let your imagination run wild!

Experience Improvements:
1. The screen stays lit while editing, giving you more time to think.
2. Timestamp editing has been optimized.
3. Capture from shortcuts!

The app is in its early stages of rapid development, so stay tuned for updates – there are always exciting features coming your way!
* 0.3.0
CLOSED: <2023-08-22>
1. Support Drafts! Now your can capture drafts!
2. a better file browser
3. Support set default location
4. move cursor quickly
5. editor support dark mode and better font color
* 0.2.1
CLOSED: <2023-08-11>
1. bugfix
* 0.2.0
CLOSED: <2023-08-07>
1. Support adding locations! Support iCloud or other file provider.
2. Support remove auto-fill mode.
3. bug fix
* 0.1.0
CLOSED: <2023-07-27>
1. An incredibly smooth editing experience.
2. Compatible with org mode version 9.3.6
3. Supports capture, agenda view, refile, log note and more.
4. Supports mini buffer and remote edit.
5. Supports multi-window editing.
6. Supports full-text search.
