#+TITLE: 更新日志
#+DATE: 2023-12-04 16:14:02 +0800
#+OPTIONS: toc:nil num:nil ^:t p:t
#+PROPERTY: SLUG changelog
#+PROPERTY: LANGUAGE zh

* 0.8.0
CLOSED: <2024-02-01 四>
终于，自定义 Capture 功能的开发和测工作完成了！这个过程不但有一些技术挑战，而且有着很大的工作量，有非常多的使用场景需要支持，单是测试工作就用了将近两周。

至此，Metanote 对 Org mode 的核心功能的支持更加完备，包括基本的文档结构，自定义任务管理，自定义 Tag 等 InBufferSettings, 自定义 Agenda view，自定义 Capture 等等，我想 Metanote 应该是在 Emacs 之外对 Org mode 支持最完整的应用了。在后面的开发工作中我们将逐渐支持富文本渲染，包括图片，表格，超链接等，以及加密，导出，Roam Research 等功能，敬请期待。

同时我们启用了公测版本，您可以同时安装正式版和测试版，加入公测，反馈问题， https://testflight.apple.com/join/pAYGdOQe (注意，测试版本可能会存在一些问题，仅供测试使用)

本次更新内容:
1. 支持自定义 Capture 功能，详细设置和使用请参考官网 https://metanote-dev.github.io/
2. 所有打开新窗口(Buffer)的功能的入口，包括 capture, agenda view, 文件管理器，收藏等，移至导航栏左侧菜单
3. “草稿”功能做为一个 Capture 模版不再独立存在，从文件管理器中移除
4. “收藏”功能独立为一个窗口(Buffer)，从文件管理器中移除
5. 优化了 MiniBuffer 和 Narrow Buffer 的功能
* 0.7.1
CLOSED: <2023-12-11>
1. 修复了无法删除日程类型自定义 Agenda view 的问题
2. 修复了编辑器菜单中有出现两个"设置"入口的问题
* 0.7.0
CLOSED: <2023-11-18>
至此 Custom agenda view 功能完整了，Org mode 中 Custom agenda view 功能的所有设置项都已支持(如果有遗漏请报问题给我们)。

下一步我们将全面支持 Custom capture 功能，敬请期待！

1. Custom agenda view 现在支持 Agenda 类型，可以按日，周，月和年时间范围查看待办事项
2. 自定义 Agenda view 可以直接保存了
3. 日程默认显示本周所有的待办事项
4. 默认全局待办列表只显示未完成项目
5. Capture 和 Agenda view 功能入口统一到了更多菜单中
6. 多个细节体验优化
* 0.6.0
CLOSED: <2023-11-03>
重磅功能，支持了自定义待办清单(Agenda View)! 可以根据 CATEGORY, TAG, PROPERTY, TODO 关键字等自定义待办清单，并可保存以供随时访问查看。

1. 支持自定义待办清单(Agenda View)
2. 支持 Tag，包括 Tag Group，详见帮助文档
3. 支持 Property，包括自定义 Property 和 Special Property，目前支持的 Special Property 包括 PRIORITY, LEVEL, TODO, ITEM, CATEGORY, 详见帮助文档
4. 支持 InBufferSettings ，详见文档，目前支持的包括 TITLE,DATE,CATEGORY,PROPERTY,TODO,SEQ_TODO,TYP_TODO,FILETAGS,TAGS
5. 窗口切换效果优化等多处体验优化
* 0.5.0
CLOSED: <2023-09-22>
Metanote 目前处于高速开发过程中，随着我们开发工作的进行，我们会带来更多便利好用的功能，并成为最好的笔记，日程和待办清单工具。感谢早期用户对我们的支持和鼓励。

1. 在这个版本中我们支持了对 Metanote 所有高级功能的一次性永久买断！
2. 支持了 iPad!
3. 支持了移动和重命名文件或文件夹。这样您就可以更方便的管理您的草稿和闪现。
4. 多个体现细节优化
* 0.4.0
CLOSED: <2023-09-08>
重大更新！
三个非常实用的功能
1. 支持本地通知了！对于编辑的计划事件，最迟事件和日程可以在安排的时间通知提醒了！
2. 支持今日聚合视图！一键查看今天要做的事！
3. 自定义待办关键字！告别 TODO 和 DONE，你可以设置自己独有的关键字，比如“稍后”，“取消”，所有你能想到的，发挥想象力，找到最合适自己的工作流！

体验优化
1. 编辑时屏幕常亮，现在可以慢慢思考了
2. 优化了时间戳的编辑
3. 支持快捷启动，闪现功能从主屏屏一键开启

App 正处于早期高速开发阶段，请保持关注和更新，总会有一些功能让你心动！
* 0.3.0
CLOSED: <2023-08-22>
1. 支持快速记录闪现
2. 更好的文件管理器
3. 支持设置默认位置
4. 更方便的移动光标
5. 编辑器支持深色模式，并优化了字体颜色
6. 优化了多个交互细节
* 0.2.1
CLOSED: <2023-08-11>
1. 问题修复
* 0.2.0
CLOSED: <2023-08-07>
1. 支持增加外部文档位置
2. 支持移除 auto-fill mode.
3. 问题修复
* 0.1.0
CLOSED: <2023-07-27>
1. 流畅丝滑的编辑体验
2. 兼容 org mode 9.3.6
3. 支持 capture, agenda view, refile, log note 等功能
4. 支持 mini buffer, remote edit
5. 支持多窗口编辑
6. 支持全文搜索
