#+TITLE: 常见问题
#+DATE: 2023-12-04 16:14:02 +0800
#+OPTIONS: toc:nil num:t ^:t
#+PROPERTY: SLUG faq
#+PROPERTY: LANGUAGE zh

* Metanote
Metanote 是一款移动端支持 org-mode 的纯文本编辑器，可以用来做知识管理和写作，做 TODO-list 或项目管理。如果您有 Org mode 的使用经验，您几乎可以毫无障碍的使用 Metanote。

即使您没有任何 org-mode 或 Emacs 经验，您也可以快速的掌握 Metanote 的使用。Metanote 的所有功能设计都是从效率出发，干净利落，回归本源。您可以毫无负担的使用 Metanote，一切皆是文本，一切比可编辑。
* 我们的使命愿景
我们致力于为所有人提供完全去中心化，绝对隐私和高度自由的知识管理和任务管理解决方案。
** 去中心化
一切基于纯文本，没有任何私有文件格式，这意味着你的数据不依赖于任何平台或软件，用户对自的数据拥有绝对的控制权，可以自由的使用，拷贝，移动，永久保存，不会因平台或软件的变动而丢失自己的数据。
** 绝对隐私
纯本地应用，纯 Native 开发，无需任何网络连接，绝对隐私。
** 高度自由
一切皆文本，一切皆可编辑。灵活自由，每个人都可以用出自己的风格，每个人都可以打造适合自己的工作流，每种需求场景都可以找到解决方案。
* Metanote 是开源软件吗？
目前 Metanote 没有开源。Metanote 是纯本地，纯 Native 的应用，不同于基于 Web 的同类产品，Metanote 没有使用门槛，我们无法保证在开源之后代码不被商业使用，一旦出现这种情况对用户也是一种困扰。
* Metanote 在不开源的情况下如何保证用户数据的隐私？
1. Metanote 除了与 iOS 系统必要的交互外(比如在付费高级功能时)无需任何网络访问，这一点无论是从iOS的隐私报告还是通过网络抓包都很容易证实。
2. Metanote 是纯 Native 应用，代码一经编译无法变更，这也是区别于基于 Web 应用的地方。
* Metanote 是免费的吗？
Metanote 基本编辑功能完全免费。同时为了完成我们的使命，Metanote 部分高级功能需要付费，Metanote 可以一次性永久买断。所有收入都将用来维持 Metanote 的开发维护工作。如果 Metanote 为您的生活工作带来价值，提升了品质，请慷慨的支持我们的开发工作。

